/** 25 options */
export const SHOT_TYPES = [
  "Bird's-Eye View",
  "Close Up",
  "Cutaway Shot",
  "Cowboy Shot",
  "Dutch Angle",
  "Entire Body",
  "Establishing Shot",
  "Extreme Close Up",
  "Group Shot",
  "Headshot",
  "High Angle Shot",
  "Insert Shot",
  "Low Angle Shot",
  "Medium Shot",
  "Over The Shoulder Shot",
  "Overhead Shot",
  "Point of View Shot",
  "Reaction Shot",
  "Reverse Shot",
  "Three Quarter Body",
  "Tight Headshot",
  "Two-Shot",
  "Upper Body",
  "Wide Shot",
  "Worm's-Eye View",
] as const;

export const LIGHTING_OPTIONS = [
  "Backlighting/Rim Light",
  "Blue Hour",
  "Bounce Lighting",
  "Broad Lighting",
  "Candlelight Lighting",
  "Chiaroscuro Lighting",
  "Color Gels",
  "Direct Flash",
  "Fog Diffusion",
  "Gobo Lighting",
  "Golden Hour",
  "Hard Lighting",
  "High Key Lighting",
  "LED Streetlights",
  "Loop Lighting",
  "Low Key Lighting",
  "Midday Sun",
  "Moonlight",
  "Motivated Lighting",
  "Natural Daylight",
  "Neon Lights",
  "Overcast Sky",
  "Practical Lights",
  "Rembrandt Lighting",
  "Soft Box",
  "Split Lighting",
  "Studio Strobe",
  "Sunset/Golden Hour",
  "Tungsten Light",
  "Window Light",
] as const;

export const CAMERA_BODIES = [
  "ARRI Alexa 65",
  "Red Digital Cinema Camera",
  "Sony Venice",
  "Panavision Panaflex",
  "Canon C500",
  "Sony FX6",
  "Sony FX3",
  "Blackmagic 6K",
  "35mm Film Camera",
  "16mm Film Camera",
  "8mm Film Camera",
  "Leica M11",
  "Hasselblad X1D II",
  "Phase One XF IQ4",
  "Canon R5",
  "Nikon Z9",
  "Fujifilm GFX100",
  "iPhone Pro",
  "GoPro Hero",
  "Polaroid 600",
  "Lomo LC-A",
  "Holga 120N",
  "Kodak Disposable",
  "ARRI Mini LF",
  "Sony FX9",
] as const;

export const FOCAL_LENGTHS = [
  "8mm Fisheye",
  "14mm Ultra Wide",
  "24mm Wide Angle",
  "35mm Standard",
  "50mm Standard",
  "85mm Portrait",
  "100mm Macro",
  "200mm Super Telephoto",
  "300mm Extreme Telephoto",
] as const;

export const LENS_TYPES = [
  "Anamorphic Cinema Lens",
  "Catadioptric Mirror Lens",
  "Fisheye Lens",
  "Helios 44-2 Swirly Bokeh",
  "Holga Style Lens",
  "Lensbaby Selective Focus",
  "Macro Lens",
  "Petzval Portrait Lens",
  "Soft-Focus Portrait Lens",
  "Tilt-Shift Lens",
  "Toy Plastic Lens",
  "Voigtländer Nokton 50mm",
] as const;

/** 110+ searchable movie / show aesthetics */
export const MOVIE_LOOKS = [
  "1917",
  "2001: A Space Odyssey",
  "Alien",
  "Amélie",
  "Annihilation",
  "Apocalypse Now",
  "Arrival",
  "Avatar",
  "Back to the Future",
  "Beetlejuice",
  "Blade Runner",
  "Blade Runner 2049",
  "Casablanca",
  "Children of Men",
  "Chinatown",
  "City of God",
  "Collateral",
  "Dark City",
  "Days of Heaven",
  "District 9",
  "Drive",
  "Dune",
  "Enter the Void",
  "Fight Club",
  "Full Metal Jacket",
  "Game of Thrones",
  "Ghostbusters",
  "Gladiator",
  "Godzilla Minus One",
  "Grease",
  "Halloween",
  "Hereditary",
  "Hook",
  "In the Mood for Love",
  "Jaws",
  "John Wick",
  "Joker",
  "Jurassic Park",
  "Kill Bill Vol 1",
  "King Kong 1933",
  "Mad Max Fury Road",
  "The Matrix",
  "Moonrise Kingdom",
  "Mulholland Drive",
  "No Country for Old Men",
  "Nosferatu",
  "Parasite",
  "Pan's Labyrinth",
  "Psycho",
  "Raiders of the Lost Ark",
  "Roma",
  "Saving Private Ryan",
  "Saw",
  "Sicario",
  "Sin City",
  "Skyfall",
  "Squid Game",
  "Stalker",
  "Star Wars A New Hope",
  "Stranger Things",
  "Suspiria 1977",
  "Terminator 2",
  "The Assassination of Jesse James",
  "The Bourne Ultimatum",
  "The Dark Crystal",
  "The Dark Knight",
  "The Exorcist",
  "The Godfather",
  "The Good The Bad The Ugly",
  "The Grand Budapest Hotel",
  "The Hurt Locker",
  "The Lighthouse",
  "The Lord of the Rings",
  "The Maltese Falcon",
  "The Neverending Story",
  "The Revenant",
  "The Ring",
  "The Shape of Water",
  "The Shining",
  "The Ten Commandments",
  "The Texas Chain Saw Massacre",
  "The Thing",
  "The Witch",
  "There Will Be Blood",
  "Titanic",
  "Trainspotting",
  "Twilight",
  "Under the Skin",
  "Utopia",
  "Who Framed Roger Rabbit",
  "Zero Dark Thirty",
  "Interstellar",
  "Inception",
  "The Social Network",
  "Spirited Away",
  "The Seventh Seal",
  "Barry Lyndon",
  "Se7en",
  "Memento",
  "Oldboy",
  "The Prestige",
  "Whiplash",
  "La La Land",
  "Birdman",
  "Her",
  "Ex Machina",
  "Eternal Sunshine of the Spotless Mind",
  "The Fall",
  "Metropolis 1927",
  "Citizen Kane",
  "Lawrence of Arabia",
  "Vertigo",
  "Rear Window",
  "North by Northwest",
  "12 Angry Men",
  "The Departed",
  "Heat",
  "Goodfellas",
  "Scarface",
  "A Clockwork Orange",
  "The Searchers",
  "Sunset Boulevard",
  "Double Indemnity",
  "The Third Man",
  "Touch of Evil",
  "Fargo",
  "Noir",
  "The Big Lebowski",
  "Pulp Fiction",
  "Reservoir Dogs",
  "Inglourious Basterds",
  "Once Upon a Time in Hollywood",
  "Seven Samurai",
  "Ran",
  "Yojimbo",
  "The Green Knight",
  "Midsommar",
  "The Northman",
] as const;
